#!/bin/bash

sufx=$(date +%Y%m%d%H%M%S)

cp --no-clobber ~/Downloads/antlr-4.13.2-complete.jar cobol/
cp --no-clobber ~/Downloads/antlr-4.13.2-complete.jar db2z/
cp --no-clobber ~/Downloads/antlr-4.13.2-complete.jar jcl/
cp --no-clobber ~/Downloads/antlr-4.13.2-complete.jar cics/
cp --no-clobber ~/Downloads/antlr-4.13.2-complete.jar dli/
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' cobol/manifest
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' jcl/manifest
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' cobol/Makefile
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' db2z/Makefile
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' jcl/Makefile
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' cics/Makefile
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' dli/Makefile
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' db2z/src/tester
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' jcl/src/tester
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' cics/src/tester
sed -i.${sufx} 's/antlr-4.13.1-complete.jar/antlr-4.13.2-complete.jar/' dli/src/tester

