#!/bin/bash

function testLexAndParse {

	while read line
	do
		java -cp "./class$sep./antlr-4.13.2-complete.jar" org.antlr.v4.gui.TestRig $kind startRule -tokens < $line 1>/dev/null 2>$tmp02
		grep -v '^\[' $tmp02
		if [ "$?" -eq 0 ]
		then
			echo $line " NOT OK"
			export myRC=12
		else
			echo $line " OK"
		fi
	done < $tmp01

}

STARTTIME=$(date +%s)
export kind=DLI
export myRC=0
export tmp01=/tmp/$(date +%Y%m%d%H%M%S).$$.mapadli01
export tmp02=/tmp/$(date +%Y%m%d%H%M%S).$$.mapadli02
if [ "$1" = "all" ]
then
  ls -Al testdata/dli_* | awk '{print $9}' > $tmp01
else
  ls -Al testdata/dli_$1 | awk '{print $9}' > $tmp01
fi

case "$OSTYPE" in
  solaris*) echo "SOLARIS" ;;
  darwin*)  echo "OSX" ;;
  linux*)   echo "LINUX" ;;
  bsd*)     echo "BSD" ;;
  msys*)    echo "WINDOWS" ;;
  cygwin*)  echo "ALSO WINDOWS" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac

export sep=":"
if [[ "$OSTYPE" == "msys"* ]]; then
  export sep=";"
fi

testLexAndParse

rm $tmp01
rm $tmp02

ENDTIME=$(date +%s)

echo "elapsed time $(($ENDTIME - $STARTTIME)) seconds"

exit $myRC

