#! /usr/bin/awk -f

#generate ANTLR keywords
#./genCPoptions -v p='CP_'
#input:
#SELECT
#output:
#SELECT: S E L E C T ;

{
	if (length($0) > 0) {
		split($0, chars, "")
		t = $0;
		gsub(" ", "_", t)
		printf("%s%s\n\t:", p, t)
		for (i=0; i<=length($0); i++) {
			if (chars[i] == "_") {
				printf("'_' ");
			} else if (chars[i] == " ") {
				printf("[ ]+ ");
			} else if (chars[i] ~ /[0-9]/) {
				printf("'%s' ", chars[i]);
			} else {
				printf("%s ", chars[i])
			}
		}
		printf("\n\t->type(%s)", t);
		printf("\n\t;\n\n");
	}
}
