#!/bin/bash

function testLexAndParse {

	while read line
	do
		java -cp ./class:.:./antlr-4.11.1-complete.jar org.antlr.v4.gui.TestRig $kind startRule -tokens < $line 1>/dev/null 2>$tmp02
		grep -v '^\[' $tmp02
		if [ "$?" -eq 0 ]
		then
			echo $line " NOT OK"
			export myRC=12
		else
			echo $line " OK"
		fi
		#java -cp ./class:.:./antlr-4.11.1-complete.jar org.antlr.v4.gui.TestRig $kind startRule -tree < $line | ./src/treeCount -vruleName=$line -vruleType=$kind
		#export myRC1=$?
		#if [ "$myRC1" -gt "$myRC" ]
		#then
		#	export myRC=$myRC1
		#fi
	done < $tmp01

}

STARTTIME=$(date +%s)
export kind=DB2zSQL
export myRC=0
export tmp01=/tmp/$(date +%Y%m%d%H%M%S).$$.mapadb2z01
export tmp02=/tmp/$(date +%Y%m%d%H%M%S).$$.mapadb2z02
if [ "$1" = "all" ]
then
  ls -Al testdata/sql_* | awk '{print $9}' > $tmp01
else
  ls -Al testdata/sql_$1 | awk '{print $9}' > $tmp01
fi

testLexAndParse

rm $tmp01
rm $tmp02

ENDTIME=$(date +%s)

echo "elapsed time $(($ENDTIME - $STARTTIME)) seconds"

exit $myRC

