#! /usr/bin/awk -f

#generate ANTLR keywords
#input:
#SELECT
#output:
#SELECT: S E L E C T ;

{
	if (length($0) > 0) {
		split($0, chars, "")
		t = $0;
		gsub("-", "_", t)
		printf("%s : ", t)
		for (i=0; i<=length($0); i++) {
			if (chars[i] == "-") {
				printf("MINUSCHAR ");
			} else if (chars[i] == " ") {
				printf("[ ]+ ");
			} else if (chars[i] ~ /[0-9]/) {
				printf("'%s' ", chars[i]);
			} else {
				printf("%s ", chars[i])
			}
		}
		printf(";\n");
	}
}
